### ISSUE TITLE
Java client seems to be broken

### ISSUE THREAD

**Issue by lloydmeta** [m3dev/octoparts#99] opened 2015-02-17 09:08 UTC
@ntaro tried to use the Java client but it failed to work properly (hitting it with AsyncHttpClient worked) in his project.

Apparently downgrading to an older version of Jackson (2.4.x?) made it work.

**Comment by mauhiz** [comment] 2015-02-24 05:18
I think the issue is that we do not support Java6 anymore (the build for the Java client is only run against Java 8) since upgrading to the latest ning async http client.

**Comment by mauhiz** [comment] 2015-02-25 04:39
Closing as this issue was likely related to Java6

**Closed by mauhiz** 2015-02-25 04:39 UTC
Labels: bug
